<template>
  <NucGridPage v-bind:gap="{'col':0,'row':0}" v-bind:rows="[1]"
    v-bind:schema="{'r0-c0':{'col':0,'row':0,'showIn':['xs','sm','md','lg'],'colSpan':1,'rowSpan':1}}"
    v-bind:columns="[1]" overflow="auto" v-bind:designMode="false" v-bind:minNsLimit="1614"
    v-bind:style="{'background':'#FFFFFF','paddingTop':'0px','paddingLeft':'0px','paddingRight':'0px','paddingBottom':'0px'}">
    <NucGridCell v-bind:wrap="true" v-bind:reverse="false" overflow="hidden" direction="column"
      v-bind:showInDevice="['xs','sm','md','lg']" verticalAlignment="top" horizontalAlignment="left"
      id="778d9caa-e59f-416b-aff9-d31da69e126b" v-bind:col="0" v-bind:row="0" v-bind:colSpan="1" v-bind:rowSpan="1"
      v-bind:marginTop="0" v-bind:marginLeft="0" v-bind:marginRight="0" v-bind:marginBottom="0"
      v-bind:style="{'height':'auto','background':'transparent','paddingTop':'0px','borderColor':'','borderStyle':'solid','borderWidth':'0px','paddingLeft':'0px','borderRadius':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'1px','borderTopRightRadius':'1px','borderBottomLeftRadius':'1px','borderBottomRightRadius':'1px'}"
      slot="r0-c0" area="r0-c0">
      <NucGroupElement top="0%" left="0%" v-bind:snapX="false" v-bind:snapY="false" v-bind:isLock="true" bgColor=""
        position="absolute" ncTooltipText="" id="8dc1833b-1663-4be9-b322-56df4f8a15c5"
        v-bind:style="{'color':'#FFFFFF','width':'1049.25px','height':'570px','zIndex':2,'fontSize':'11.25px','maxWidth':'','minWidth':'7.5','tabIndex':'-0.75','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'7.5','textAlign':'center','background':'','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.9375','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderColor':'#767676','borderStyle':'solid','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.75px','textDecoration':'none','borderLeftWidth':'0.75px','borderRightWidth':'0.75px','borderBottomWidth':'0.75px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}">
        <NucGroupElement top="4.730617608409987%" left="0.07132667617689016%" v-bind:snapX="false" v-bind:snapY="false"
          bgColor="" position="absolute" ncTooltipText="" id="48ac2e19-ae82-48fa-a1d3-f4e3bdd2ef36"
          v-bind:style="{'color':'#FFFFFF','width':'1614.75px','height':'88.5px','zIndex':4,'fontSize':'11.25px','maxWidth':'','minWidth':'7.5','tabIndex':'-0.75','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'7.5','textAlign':'center','background':'#022b56','fontFamily':'Roboto-Regular,Roboto','fontWeight':'normal','lineHeight':'0.9375','marginLeft':'0px','paddingTop':'','textShadow':'','visibility':'visible','borderColor':'#767676','borderStyle':'solid','marginRight':'0px','paddingLeft':'','marginBottom':'0px','paddingRight':'','paddingBottom':'','borderTopWidth':'0.75px','textDecoration':'none','borderLeftWidth':'0.75px','borderRightWidth':'0.75px','borderBottomWidth':'0.75px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}">
          <WImage top="32.20338983050848%" left="7.659269863994274%" v-bind:blank="false" v-bind:snapX="false"
            v-bind:snapY="false" v-bind:rounded="false" stretch="none"
            imageUrl="https://simplar.atakansaracoglu.com/wp-content/uploads/elementor/thumbs/simplar-logo-light-pfjjv721dh8fum3hov6zq87i60hbahainwcyeqty1c.png"
            position="absolute" v-bind:isEnabled="true" v-bind:thumbnail="false" blankColor="black"
            v-bind:aspectRatio="true" dataLoading="static" ncTooltipText="Please write a text to display in tooltip..."
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModelForDynamicType'},'propName':'imageUrl','displayName':'Value'}]}"
            ncClickBorderColor="black" ncHoverBorderColor="black" dataModelForDynamicType="string"
            id="4592dce7-75ea-4316-8304-a6e5212d032b"
            v-bind:style="{'width':'','height':'','zIndex':6,'maxWidth':'','minWidth':'','boxShadow':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','borderColor':'#4B74FF','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}"/>
          <TwSimpleDropdown top="31.896551724137932%" left="28.602150537634408%" v-bind:snapX="false"
            v-bind:snapY="false" v-bind:options="[]" itemHref="#" position="absolute" v-bind:selected="[]" dataModel=""
            itemWidth="tw-w-36" itemRadius="tw-rounded-md" itemShadow="tw-shadow-lg" buttonColor="tw-bg-blue-900"
            buttonLabel="Home" buttonWidth="tw-w-full" cardDisplay="tw-inline-block" dataLoading=""
            itemBgColor="tw-bg-transparent" itemDisplay="tw-block" buttonShadow="tw-shadow-sm" itemFontSize="tw-text-xl"
            buttonDisplay="tw-inline-flex" buttonJustify="tw-justify-center" dataModelType=""
            itemTextColor="tw-text-slate-50" ncTooltipText="" buttonFontSize="tw-text-2xl"
            itemFontWeight="tw-font-normal"
            v-bind:nucalDataModel="{'type':'NSW','isList':true,'update':{'dataModel':'dataModel'},'dynamic':true,'dataModel':'','structure':[{'type':'','update':{'type':'dataModelType','dataModel':'dataModel'},'propName':'options','dataModel':'','displayName':'Value'}]}"
            buttonIconWidth="tw-w-8" buttonTextColor="tw-text-slate-50" itemShadowColor="tw-shadow-transparent"
            buttonFontWeight="tw-font-normal" buttonHoverColor="tw-bg-gray-50" buttonIconHeight="tw-h-12"
            allTextItemsAlign="tw-text-left" buttonBorderColor="tw-border-transparent" buttonBorderWidth="tw-border"
            buttonShadowColor="tw-shadow-transparent" buttonBorderRadius="tw-rounded-md"
            id="1700ab42-f448-4b14-884c-f479c199ca28"
            v-bind:style="{'width':'90px','height':'35.25px','zIndex':7,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
          <TwPrimaryButton top="33.62068965517241%" left="35.1931330472103%" v-bind:snapX="false" v-bind:snapY="false"
            position="absolute" buttonHref="#" buttonColor="tw-bg-transparent" buttonLabel="About Us"
            buttonDisplay="tw-inline-flex" ncTooltipText="" buttonFontSize="tw-text-lg"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'buttonLabel','displayName':'ButtonLabel'}]}"
            buttonTextColor="tw-text-white" buttonFontFamily="tw-font-sans" buttonFontWeight="tw-font-normal"
            buttonHoverColor="tw-bg-indigo-700" buttonBorderColor="tw-border-transparent" buttonBorderWidth="tw-border"
            buttonBorderRadius="tw-rounded-md" buttonBorderShadow="tw-shadow-sm" buttonTextAlignment="tw-items-center"
            buttonJustifyContent="tw-justify-center" buttonBorderShadowColor="tw-shadow-transparent"
            id="865c5945-5f2f-47ed-a457-3acae8e2826b"
            v-bind:style="{'width':'121.5px','height':'35.25px','zIndex':8,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
          <TwPrimaryButton top="33.05084745762712%" left="42.642857142857146%" v-bind:snapX="false" v-bind:snapY="false"
            position="absolute" buttonHref="#" buttonColor="tw-bg-transparent" buttonLabel="Services"
            buttonDisplay="tw-inline-flex" ncTooltipText="" buttonFontSize="tw-text-lg"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'buttonLabel','displayName':'ButtonLabel'}]}"
            buttonTextColor="tw-text-white" buttonFontFamily="tw-font-sans" buttonFontWeight="tw-font-normal"
            buttonHoverColor="tw-bg-indigo-700" buttonBorderColor="tw-border-transparent" buttonBorderWidth="tw-border"
            buttonBorderRadius="tw-rounded-md" buttonBorderShadow="tw-shadow-sm" buttonTextAlignment="tw-items-center"
            buttonJustifyContent="tw-justify-center" buttonBorderShadowColor="tw-shadow-transparent"
            id="c7f605d3-de31-4501-9188-ad19cd8bf5ce"
            v-bind:style="{'width':'118.5px','height':'35.25px','zIndex':9,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
          <TwPrimaryButton top="32.20338983050848%" left="50.285714285714285%" v-bind:snapX="false" v-bind:snapY="false"
            position="absolute" buttonHref="#" buttonColor="tw-bg-transparent" buttonLabel="Portfolio"
            buttonDisplay="tw-inline-flex" ncTooltipText="" buttonFontSize="tw-text-lg"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'buttonLabel','displayName':'ButtonLabel'}]}"
            buttonTextColor="tw-text-white" buttonFontFamily="tw-font-sans" buttonFontWeight="tw-font-normal"
            buttonHoverColor="tw-bg-indigo-700" buttonBorderColor="tw-border-transparent" buttonBorderWidth="tw-border"
            buttonBorderRadius="tw-rounded-md" buttonBorderShadow="tw-shadow-sm" buttonTextAlignment="tw-items-center"
            buttonJustifyContent="tw-justify-center" buttonBorderShadowColor="tw-shadow-transparent"
            id="63f553a0-5aed-43ca-97fb-2ddd55461bc2"
            v-bind:style="{'width':'118.5px','height':'35.25px','zIndex':10,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
          <TwPrimaryButton top="32.20338983050848%" left="58.785714285714285%" v-bind:snapX="false" v-bind:snapY="false"
            position="absolute" buttonHref="#" buttonColor="tw-bg-transparent" buttonLabel="References"
            buttonDisplay="tw-inline-flex" ncTooltipText="" buttonFontSize="tw-text-lg"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'buttonLabel','displayName':'ButtonLabel'}]}"
            buttonTextColor="tw-text-white" buttonFontFamily="tw-font-sans" buttonFontWeight="tw-font-normal"
            buttonHoverColor="tw-bg-indigo-700" buttonBorderColor="tw-border-transparent" buttonBorderWidth="tw-border"
            buttonBorderRadius="tw-rounded-md" buttonBorderShadow="tw-shadow-sm" buttonTextAlignment="tw-items-center"
            buttonJustifyContent="tw-justify-center" buttonBorderShadowColor="tw-shadow-transparent"
            id="493b47de-c7d7-4f19-ac19-3e60438a37da"
            v-bind:style="{'width':'118.5px','height':'35.25px','zIndex':11,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
          <TwPrimaryButton top="33.898305084745765%" left="68.28571428571429%" v-bind:snapX="false" v-bind:snapY="false"
            position="absolute" buttonHref="#" buttonColor="tw-bg-transparent" buttonLabel="Latest News"
            buttonDisplay="tw-inline-flex" ncTooltipText="" buttonFontSize="tw-text-lg"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'buttonLabel','displayName':'ButtonLabel'}]}"
            buttonTextColor="tw-text-white" buttonFontFamily="tw-font-sans" buttonFontWeight="tw-font-normal"
            buttonHoverColor="tw-bg-indigo-700" buttonBorderColor="tw-border-transparent" buttonBorderWidth="tw-border"
            buttonBorderRadius="tw-rounded-md" buttonBorderShadow="tw-shadow-sm" buttonTextAlignment="tw-items-center"
            buttonJustifyContent="tw-justify-center" buttonBorderShadowColor="tw-shadow-transparent"
            id="81d596e5-6065-48c3-9c53-a80f29e42677"
            v-bind:style="{'width':'118.5px','height':'35.25px','zIndex':12,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
          <WButton tag="button" top="22.88135593220339%" left="80.31496062992126%" v-bind:pill="false" size="md"
            text="Contact us" type="button" v-bind:block="false" color="" v-bind:snapX="false" v-bind:snapY="false"
            theme="theme--light01" v-bind:squared="false" variant="primary" ncBgType="bgColor" position="absolute"
            v-bind:isEnabled="true" background="#1a6ec6" borderColor="#007bff" ncTypography="custom"
            v-bind:resetTrigger="false" ncTooltipText="" verticalWidth="60px"
            v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
            textDecoration="none" verticalHeight="60px" horizontalWidth="72.4479px" nucalScaleWidth=""
            horizontalHeight="37.5347px" ncClickFontColor="#FFFFFF" ncFocusFontColor="#FFFFFF"
            ncHoverFontColor="#FFFFFF" nucalScaleHeight="" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
            ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" ncDisableBorderColor="transparent"
            ncClickBackgroundColor="#4285f4" ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4"
            ncDisableBackgroundColor="#969696" id="347bbffd-8489-47cf-a1c0-3fc6b3b6b0ee"
            v-bind:style="{'width':'123.75px','height':'48.75px','zIndex':13,'fontSize':'15.75px','maxWidth':'','minWidth':'','tabIndex':'0px','boxShadow':'','fontStyle':'normal','marginTop':'','maxHeight':'','minHeight':'','textAlign':'center','fontFamily':'OpenSans-SemiBold,Open Sans','fontWeight':'normal','lineHeight':'1.0499999999999998','marginLeft':'','paddingTop':'','textShadow':'','visibility':'visible','borderStyle':'solid','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','paddingBottom':'','borderTopWidth':'0.75px','textDecoration':'none','borderLeftWidth':'0.75px','borderRightWidth':'0.75px','horizontalHeight':'28.151025px','borderBottomWidth':'0.75px','borderTopLeftRadius':'3px','borderTopRightRadius':'3px','borderBottomLeftRadius':'3px','borderBottomRightRadius':'3px'}"/>
        </NucGroupElement>
        <WInput id="cdfbe0ac-f681-48ab-9c5f-69b7104f0277" top="0.7915567282321899%" v-bind:lazy="false"
          left="10.236220472440944%" size="md" step="" text="info@ulmer-agentur.de" v-bind:trim="false"
          v-bind:snapX="false" v-bind:snapY="false" v-bind:noWheel="false" v-bind:disabled="false" position="absolute"
          v-bind:readonly="false" v-bind:required="false" wordList="" v-bind:autofocus="false" v-bind:plaintext="true"
          background="" ariaInvalid="false" v-bind:debounceVal="0" ncInputType="text" placeholder="Enter something..."
          v-bind:previewMode="true" autocomplete="" ncTypography="custom" v-bind:lazyFormatter="false" ncTooltipText=""
          v-bind:isWordListOpen="false"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','ncKey':'type','ncType':{'ncInputType':'number'},'ncValue':'number','propName':'text','displayName':'Value','nsDefaultValue':'string'}]}"
          v-bind:isNumberConvert="false" ncClickFontColor="#434855" ncFocusFontColor="#434855"
          ncHoverFontColor="#434855" ncMaxNumberValue="100" ncMinNumberValue="0" ncClickBorderColor="#000000"
          ncDisableFontColor="#434855" ncFocusBorderColor="#000000" ncHoverBorderColor="#000000"
          ncDisableBorderColor="#000000" formatterFunctionName="" ncClickBackgroundColor="#ffffff"
          ncFocusBackgroundColor="#ffffff" ncHoverBackgroundColor="#ffffff" ncDisableBackgroundColor="#ffffff"
          v-bind:style="{'color':'','width':'162.75px','height':'18px','zIndex':5,'fontSize':'12px','maxWidth':'','minWidth':'118.5px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'OpenSans-SemiBold,Open Sans','fontWeight':'normal','lineHeight':'0.75','marginLeft':'0px','paddingTop':'0px','visibility':'visible','borderColor':'#D1D1D6','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'underline'}"/>
        <WIconButton tag="button" top="1.0498687664041995%" icon="fas fa-envelope" left="7.301360057265569%"
          v-bind:pill="false" size="sm" text="BUT" type="button" v-bind:block="false" color="#FFFFFF"
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
          fontSize="4px" position="absolute" fontStyle="normal" iconColor="#022b56" v-bind:isEnabled="true"
          minHeight="2px" background="#ffffff" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400"
          layoutMode="left-to-right" lineHeight="1.2" textShadow="" borderColor="#6C757D" iconFontSize="20px"
          ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
          iconFontFamily="font-awesome"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
          horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
          ncFocusBorderColor="#4285f4" ncHoverBorderColor="#FFFFFF" buttonTextAlignment="center"
          horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
          ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#FFFFFF" ncDisableBackgroundColor="#4285f4"
          id="4378e9b3-738f-4721-ba66-6d193e92d22d"
          v-bind:style="{'width':'31.5px','height':'17.25px','zIndex':6,'maxWidth':'','minWidth':'1.5px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'none','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0.75px','borderLeftWidth':'0.75px','borderRightWidth':'0.75px','borderBottomWidth':'0.75px','borderTopLeftRadius':'3px','borderTopRightRadius':'3px','borderBottomLeftRadius':'3px','borderBottomRightRadius':'3px'}"/>
        <WIconButton tag="button" top="0.6561679790026247%" icon="fas fa-phone-square-alt" left="36.22047244094488%"
          v-bind:pill="false" size="sm" text="BUT" type="button" v-bind:block="false" color="#FFFFFF"
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" v-bind:squared="false" variant="secondary"
          fontSize="4px" position="absolute" fontStyle="normal" iconColor="#022b56" v-bind:isEnabled="true"
          minHeight="2px" background="#ffffff" fontFamily="OpenSans-Bold,Open Sans" fontWeight="400"
          layoutMode="left-to-right" lineHeight="1.2" textShadow="" borderColor="#6C757D" iconFontSize="20px"
          ncTypography="custom" iconAlignment="center" iconFontStyle="default" ncTooltipText="" verticalWidth=""
          iconFontFamily="font-awesome"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          textDecoration="none" verticalHeight="" horizontalWidth="" horizontalHeight="" ncClickFontColor="#FFFFFF"
          ncFocusFontColor="#FFFFFF" ncHoverFontColor="#FFFFFF" verticalMinWidth="40px" verticalMinHeight="60px"
          horizontalMinWidth="96px" ncClickBorderColor="#4285f4" ncDisableFontColor="#FFFFFF"
          ncFocusBorderColor="#4285f4" ncHoverBorderColor="#4285f4" buttonTextAlignment="center"
          horizontalMinHeight="30px" ncDisableBorderColor="#4285f4" ncClickBackgroundColor="#4285f4"
          ncFocusBackgroundColor="#4285f4" ncHoverBackgroundColor="#4285f4" ncDisableBackgroundColor="#4285f4"
          id="14f5477e-609c-43d2-a8d6-07521ba4966d"
          v-bind:style="{'width':'25.5px','height':'22.5px','zIndex':7,'maxWidth':'','minWidth':'1.5px','tabIndex':'0px','boxShadow':'','marginTop':'','maxHeight':'','marginLeft':'','paddingTop':'','visibility':'visible','borderStyle':'none','marginRight':'','paddingLeft':'','marginBottom':'','paddingRight':'','hasDesignMode':true,'paddingBottom':'','borderTopWidth':'0.75px','borderLeftWidth':'0.75px','borderRightWidth':'0.75px','borderBottomWidth':'0.75px','borderTopLeftRadius':'3px','borderTopRightRadius':'3px','borderBottomLeftRadius':'3px','borderBottomRightRadius':'3px'}"/>
        <WInput id="bc1ed455-623b-494a-8f75-906c9b9903dd" top="0.5277044854881267%" v-bind:lazy="false"
          left="38.797423049391554%" size="md" step="" text="+49 123 456 7890" v-bind:trim="false" v-bind:snapX="false"
          v-bind:snapY="false" v-bind:noWheel="false" v-bind:disabled="false" position="absolute"
          v-bind:readonly="false" v-bind:required="false" wordList="" v-bind:autofocus="false" v-bind:plaintext="true"
          background="" ariaInvalid="false" v-bind:debounceVal="0" ncInputType="text" placeholder="Enter something..."
          v-bind:previewMode="true" autocomplete="" ncTypography="custom" v-bind:lazyFormatter="false" ncTooltipText=""
          v-bind:isWordListOpen="false"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','ncKey':'type','ncType':{'ncInputType':'number'},'ncValue':'number','propName':'text','displayName':'Value','nsDefaultValue':'string'}]}"
          v-bind:isNumberConvert="false" ncClickFontColor="#434855" ncFocusFontColor="#434855"
          ncHoverFontColor="#434855" ncMaxNumberValue="100" ncMinNumberValue="0" ncClickBorderColor="#000000"
          ncDisableFontColor="#434855" ncFocusBorderColor="#000000" ncHoverBorderColor="#000000"
          ncDisableBorderColor="#000000" formatterFunctionName="" ncClickBackgroundColor="#ffffff"
          ncFocusBackgroundColor="#ffffff" ncHoverBackgroundColor="#ffffff" ncDisableBackgroundColor="#ffffff"
          v-bind:style="{'color':'#000000','width':'135.75px','height':'23.25px','zIndex':8,'fontSize':'12px','maxWidth':'','minWidth':'118.5px','boxShadow':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'OpenSans-SemiBold,Open Sans','fontWeight':'normal','lineHeight':'0.75','marginLeft':'0px','paddingTop':'0px','visibility':'visible','borderColor':'#D1D1D6','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'underline'}"/>
        <WImage top="19.736842105263158%" left="0%" v-bind:blank="false" v-bind:snapX="false" v-bind:snapY="false"
          v-bind:rounded="false" stretch="none"
          imageUrl="https://simplar.atakansaracoglu.com/wp-content/uploads/2021/11/AdobeStock_339771292-scaled.jpeg"
          position="absolute" v-bind:isEnabled="true" v-bind:thumbnail="false" blankColor="black"
          v-bind:aspectRatio="true" dataLoading="static" ncTooltipText="Please write a text to display in tooltip..."
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModelForDynamicType'},'propName':'imageUrl','displayName':'Value'}]}"
          ncClickBorderColor="black" ncHoverBorderColor="black" dataModelForDynamicType="string"
          id="59e8f07b-39a5-44cd-a44a-d046cfaadb02"
          v-bind:style="{'width':'1046.25px','height':'456px','zIndex':9,'maxWidth':'','minWidth':'','boxShadow':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','borderColor':'#4B74FF','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}"/>
        <WImage top="66.84210526315789%" left="19.15654038598999%" v-bind:blank="false" v-bind:snapX="false"
          v-bind:snapY="false" v-bind:rounded="false" stretch="none"
          imageUrl="https://www.linkpicture.com/q/360_F_215702641_LBZwxehoMXyY44EPY20vz2mce6bcpeM0_prev_ui.png"
          position="absolute" v-bind:isEnabled="true" v-bind:thumbnail="false" blankColor="black"
          v-bind:aspectRatio="true" dataLoading="static" ncTooltipText="Please write a text to display in tooltip..."
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':true,'structure':[{'type':'string','update':{'type':'dataModelForDynamicType'},'propName':'imageUrl','displayName':'Value'}]}"
          ncClickBorderColor="black" ncHoverBorderColor="black" dataModelForDynamicType="string"
          id="f7fab33f-9549-448d-99f3-75e353cfd19c"
          v-bind:style="{'width':'96px','height':'67.5px','zIndex':13,'maxWidth':'','minWidth':'','boxShadow':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','borderColor':'#4B74FF','borderStyle':'solid','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','borderTopWidth':'0px','borderLeftWidth':'0px','borderRightWidth':'0px','borderBottomWidth':'0px','borderTopLeftRadius':'0px','borderTopRightRadius':'0px','borderBottomLeftRadius':'0px','borderBottomRightRadius':'0px'}"/>
        <TwPrimaryButton top="69.55380577427822%" left="10.164638511095204%" v-bind:snapX="false" v-bind:snapY="false"
          position="absolute" buttonHref="#" buttonColor="tw-bg-transparent" buttonLabel="Buy Now"
          buttonDisplay="tw-inline-flex" ncTooltipText="" buttonFontSize="tw-text-2xl"
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'buttonLabel','displayName':'ButtonLabel'}]}"
          buttonTextColor="tw-text-white" buttonFontFamily="tw-font-sans" buttonFontWeight="tw-font-medium"
          buttonHoverColor="tw-bg-indigo-700" buttonBorderColor="tw-border-gray-900" buttonBorderWidth="tw-border"
          buttonBorderRadius="tw-rounded-md" buttonBorderShadow="tw-shadow-sm" buttonTextAlignment="tw-items-center"
          buttonJustifyContent="tw-justify-center" buttonBorderShadowColor="tw-shadow-transparent"
          id="4f97ad05-cd5d-4cd6-bfce-2a4e832e2652"
          v-bind:style="{'width':'108.75px','height':'35.25px','zIndex':14,'maxWidth':'','minWidth':'','marginTop':'0px','maxHeight':'','minHeight':'','marginLeft':'0px','paddingTop':'0px','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px'}"/>
        <WLabel top="30.738786279683378%" left="8.303507516105942%" text="BUSINESS THEME
CREATED FOR SUCCESS"
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom"
          ncTooltipText=""
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          id="eaa5531e-d73e-4533-add8-2c88b8cc9e4c"
          v-bind:style="{'color':'#ffffff','width':'513.75px','height':'104.25px','zIndex':15,'fontSize':'45px','maxWidth':'','minWidth':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'OpenSans-Bold,Open Sans','fontWeight':'normal','lineHeight':'0.7874999999999999','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'none'}"/>
        <WLabel top="53.026315789473685%" left="8.506075768406005%"
          text="Simplar comes with the huge power of Elementor, which offers great capabilities to edit and style options."
          v-bind:snapX="false" v-bind:snapY="false" theme="theme--light01" position="absolute" ncTypography="custom"
          ncTooltipText=""
          v-bind:nucalDataModel="{'type':'NSW','isList':false,'dynamic':false,'structure':[{'type':'string','propName':'text','displayName':'Value'}]}"
          id="c8882b35-1370-4c0e-a15d-d1bbdda0edfe"
          v-bind:style="{'color':'#ffffff','width':'503.25px','height':'42.75px','zIndex':18,'fontSize':'18.75px','maxWidth':'','minWidth':'','fontStyle':'normal','marginTop':'0px','maxHeight':'','minHeight':'','textAlign':'left','fontFamily':'OpenSans-Regular,Open Sans','fontWeight':'normal','lineHeight':'0.7874999999999999','marginLeft':'0px','paddingTop':'0px','textShadow':'','visibility':'visible','marginRight':'0px','paddingLeft':'0px','marginBottom':'0px','paddingRight':'0px','paddingBottom':'0px','textDecoration':'none'}"/>
      </NucGroupElement>
    </NucGridCell>
  </NucGridPage>
</template>
<script>
export default {
  name: 'Screen1',
  data() {
    return {};
  },
  props: {},
  created() {},
  mounted() {},
  computed: {},
  methods: {},
  watch: {},
};
</script>

<style scoped></style>